theme: minima
title: Akshansh Kumar
baseurl: "/akshanshkmr"
url: "https://akshanshkmr.github.io"
description: Senior Software Engineer · Python & React · D. E. Shaw
markdown: GFM
header_pages:
  - resume/resume.md

plugins:
  - jekyll-readme-index
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - resume/resume.md